kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: cluster-config
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
