apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  labels:
    gitops.ownedBy: app-admin-nonprod
  name: devops-admin-cicd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app-admin-nonprod
  source:
    path: environments/devops/cicd
    repoURL: https://github.com/pittar-gitops/projects-admin.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
