apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/01-groups-and-membership
patchesJson6902:
- target:
    group: user.openshift.io
    version: v1
    kind: Group
    name: argocdadmins
  path: argocdadmins-group-users.yaml
- target:
    group: user.openshift.io
    version: v1
    kind: Group
    name: developer
  path: developer-group-users.yaml
