kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  labels:
    gitops.ownedBy: cluster-config
  name: sealed-secrets
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: nonprod/01-sealed-secrets
    repoURL: https://github.com/pittar-gitops/02-admin-clusters.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
