kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  labels:
    gitops.ownedBy: cluster-config
  name: cluster-operator-instances
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config
  source:
    path: cluster-nonprod/04-cluster-operator-instances
    repoURL: https://github.com/pittar-gitops/clusters.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
