apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Argo CD expects AppProject and Application CRs in the "argocd" namespace.
namespace: argocd

# Admin and Team Argo CD Applications for the cicd, dev, and uat environments.
resources:
  # CI/CD environment
  - cicd/team-app.yaml
  # DEV envorinment
  - dev/admin-app.yaml
  - dev/team-app.yaml
  # UAT envorinment
  - uat/admin-app.yaml
  - uat/team-app.yaml