apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "14"
  name: operators-nonprod
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: cluster-config-nonprod
  source:
    path: cluster-nonprod/04-operators
    repoURL: https://github.com/clusters.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
