apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # DEV envorinment
  - dev/admin-app.yaml
  - dev/team-app.yaml
  # UAT envorinment
  - uat/admin-app.yaml
  - uat/team-app.yaml