apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "21"
  name: petclinic-team-dev
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: app-team-nonprod
  source:
    path: environments/petclinic/dev
    repoURL: https://github.com/pittar-gitops/projects-team.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
