# Assumes the cluster admin had pre-created the sealed-secrets project and secret.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sealed-secrets
bases:
- github.com/redhat-canada-gitops/01-cluster-config/manifests/sealed-secrets/base?ref=updates-sealedsecrets
resources:
- role-anyuid.yaml
